### ISSUE TITLE
Release build fails

### ISSUE THREAD

**Issue by PkmX** [lowRISC/riscv-llvm#48]
https://github.com/lowRISC/riscv-llvm/blob/6bdf271fbe604064a6f0eed26d07d777ee71ddf7/0051-LegalizeDAG-promote-PREFETCH-operands-to-native-inte.patch#L31

This should be guarded with `#ifndef NDEBUG` or removed, since the function isn't defined in release builds:
```
lib/CodeGen/SelectionDAG/LegalizeIntegerTypes.cpp:1340: undefined reference to `llvm::SDNode::dump(llvm::SelectionDAG const*) const'
```

**Comment by asb** [comment]
Thanks! That was code added while debugging the initial implementation that should have been removed. Now fixed.
