### ISSUE TITLE
riscv64 crashes on global variable access

### ISSUE THREAD

**Issue by Lichtso** [lowRISC/riscv-llvm#65]
`clang -target riscv64-unknown-elf -O3 -S mem.c`

```
unsigned int gloVar;

int main(int argc, char** argv) {
    gloVar = 42;
    return 0;
}
```

```
; ModuleID = 'mem.c'
source_filename = "mem.c"
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n64-S128"
target triple = "riscv64-unknown-unknown-elf"

@gloVar = common dso_local local_unnamed_addr global i32 0, align 4

; Function Attrs: norecurse nounwind writeonly
define dso_local signext i32 @main(i32 signext %argc, i8** nocapture readnone %argv) local_unnamed_addr #0 {
entry:
  store i32 42, i32* @gloVar, align 4, !tbaa !2
  ret i32 0
}

attributes #0 = { norecurse nounwind writeonly "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 8.0.0 (https://git.llvm.org/git/clang.git 6c59a8e68d93b90a77951a24724782f584bfebbd) (https://git.llvm.org/git/llvm.git 59913e3c6492bb8d03af2804ae143182c7a21f5b)"}
!2 = !{!3, !3, i64 0}
!3 = !{!"int", !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C/C++ TBAA"}

```

> fatal error: error in backend: Cannot select: t15: ch = store<(store 4 into @gloVar, !tbaa !2), trunc to i32> t0, Constant:i64<42>, t19, undef:i64
>   t14: i64 = Constant<42>
>   t19: i64 = ADDI t18, TargetGlobalAddress:i64<i32* @gloVar> 0 [TF=1]
>     t18: i64 = LUI TargetGlobalAddress:i64<i32* @gloVar> 0 [TF=2]
>       t16: i64 = TargetGlobalAddress<i32* @gloVar> 0 [TF=2]
>     t17: i64 = TargetGlobalAddress<i32* @gloVar> 0 [TF=1]
>   t8: i64 = undef
> In function: main
> clang-8: error: clang frontend command failed with exit code 70 (use -v to see invocation)
> clang version 8.0.0 (https://git.llvm.org/git/clang.git 6c59a8e68d93b90a77951a24724782f584bfebbd) (https://git.llvm.org/git/llvm.git 59913e3c6492bb8d03af2804ae143182c7a21f5b)
> Target: riscv64-unknown-unknown-elf
> Thread model: posix

**Comment by Hoblovski** [comment]
With asb's patches I am able to compile your code.

You should not use upstream clang/llvm, but instead the patched ones for RV64 dev.

**Comment by Lichtso** [comment]
I see, thx.
