### ISSUE TITLE
Fix torture suite cases failing due to fixup value out of range

### ISSUE THREAD

**Issue by asb** [lowRISC/riscv-llvm#9]
This affects:
* 20021120-1
* pr58574
* 20021120-1

**Comment by dvc94ch** [comment]
Also happens when compiling libcore with opt-level > 1. (opt-level = 0 disables inlining so currently only compiles with opt-level = 1)

Before you close the issue let me check weather it's fixed there too...

**Comment by asb** [comment]
How is https://github.com/lowRISC/riscv-llvm/blob/master/0033-RISCV-Implement-support-for-the-BranchRelaxation-pas.patch working for you? It certainly resolves the torture suite issues.

**Comment by asb** [comment]
Closing, as branch relaxation seems to have resolved all these issues.
